### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by Angy-h** [Angy-h/whatday_today_app#26]
### 概要
 - ページをクリックしたその日について、日本の暦を教えてくれるサービスです。
 - 季節、旬の食べ物などのトピックの中から暦に関する簡単なクイズを出し、小さなアクティビティを提案します。
 - その日についてのメッセージを投稿する機能があり、ユーザー間で共有できます。
 
### 実装予定の機能
- [ ] 暦に関する情報の表示機能
- [ ] ユーザー登録・編集・削除機能
- [ ] 投稿登録・編集・削除機能
- [ ] 写真アップロード・削除（ユーザーアバター・投稿の添付写真）
- [ ] 基本的なログイン機能

### 必要なページ
- [ ] Topページ
- [ ] ユーザー詳細ページ
- [ ] 投稿編集ページ

**Comment by Tsuchiya2** [comment]
<img width="762" alt="image" src="https://github.com/Angy-h/whatday_today_app/assets/61481161/ce9b0de9-636f-498e-8475-1e9ac6e1a6df">

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムを確認して、上記が確認できる状態でご提出をお願いいたします。

**Comment by Angy-h** [comment]
ご確認ありがとうございます。
下記のようにpublicに設定しておりますが、別の箇所を設定する必要がありますでしょうか？
ご教示いただけますと幸いです。
<img width="985" alt="スクリーンショット 2024-05-02 12 59 08" src="https://github.com/Angy-h/whatday_today_app/assets/140281190/769bf679-e51c-410e-af1d-6deb25d9759f">

**Comment by Angy-h** [comment]
先ほど、Link a projectでProjectを追加しました。
こちらでご確認いただけるか、みていただけますでしょうか。
どうぞよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
確認できました。
以下コメントになります。

---

ストーリーポイント5を付けているカードですが、おそらく見通しが不透明なためポイント5を付けたのではないかと推測しました。ストーリーポイント1,2になるくらいまで細分化すると、分かっている部分、分かっていない部分が可視化されますし、進捗を感じながら開発を進めることができます。

（〇〇について調査など、細かくissue化してOKです）

**Comment by Angy-h** [comment]
レビューとコメントありがとうございます。
特にストーリーポイントに5をつけたものについて、見直しました。
作業を分けられるものは細分化し、作業の内容を明確に文字化して、1や2になるか検討しました。
DBに関しては、実装の難易度よりも分量が多いので時間がかかると思っていました。
当初からAIの力を借りることを想定していましたので、それを明記することによって時間の目安を見積もることができました。
お手数をおかけしますが、再度レビューをお願いできますでしょうか。
どうぞよろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
確認しました。
概ね良さそうです。
LGTMです！
